# Base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Install dbt dependencies
RUN pip install --no-cache-dir dbt-bigquery

# Copy dbt project files into the container
COPY etl/dbt/ /app/dbt/

# Set the entry point to run dbt commands
CMD ["dbt", "run", "--profiles-dir", "/app/dbt"]
