# Base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy API connector code into the container
COPY api_connectors/ /app/api_connectors/

# Set the command to run the API connectors
CMD ["python", "/app/api_connectors/kafka_publisher.py"]
