# Base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Install necessary system packages
RUN apt-get update && apt-get install -y \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy the api_connectors code
COPY api_connectors/ ./api_connectors/

# Copy requirements and install them
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Set the default command to run the Lambda handler (or entry script)
CMD ["python", "api_connectors/aws_lambda_handler.py"]
