version: '3.8'

services:
  api_connectors:
    build:
      context: .
      dockerfile: docker/api_connectors/dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=example
      - AWS_SECRET_ACCESS_KEY=example
    volumes:
      - ./api_connectors:/app/api_connectors
    restart: always

  etl:
    build:
      context: .
      dockerfile: docker/etl/dockerfile
    volumes:
      - ./etl:/app/etl
    environment:
      - AWS_ACCESS_KEY_ID=example
      - AWS_SECRET_ACCESS_KEY=example
    restart: always
